obstacle_range: 2.0
raytrace_range: 3.0

inflation_radius: 1.0  #0.3 is stablish #0.5 old #2.0 old
cost_scaling_factor: 10.0 #default 10
#footprint: [[0.2, 0.0], [0.0, 0.25], [-0.25, 0.25], [-0.25, -0.25], [0.0, -0.25]]
footprint: [[0.2, 0.0], [0.1, 0.25], [-0.25, 0.25], [-0.30, 0.00], [-0.25, -0.25], [0.1, -0.25]]
track_unknown_space: true

#a list of the lasers passing data to the program, and kinect in future
observation_sources: laser_scan_sensor point_cloud_sensor sicklms_sensor

#a description of the sensor
#sensor_frame the frame of the data. Transform required?
#data_type type of data. pretty sure this is a LaserScan
#topic where to get the data
#marking add obstacles to cost map, default: true
#clearing remove obstacles from cost map, default: true
laser_scan_sensor: {sensor_frame: camera_link, data_type: LaserScan, topic: scan, marking: true, clearing: true, inf_is_valid: true} 

point_cloud_sensor: {sensor_frame: sonar_frame, data_type: PointCloud, topic: RosAria/sonar, marking: true, clearing: true, observation_persistence: 0.0, expected_update_rate: 1.0, obstacle_range: 0.7}

#sicklms_sensor: {sensor_frame: laser, data_type: LaserScan, topic: scan2, marking: true, clearing: true}
