#global_frame determines where the costmap will run
#robot_base_frame determines the frame for the base of the robot
#update_frequency in hertz
#static_map are you using a map server
global_costmap:
     global_frame: /map
     robot_base_frame: base_link
     update_frequency: 10.0   #5.0
     static_map: true
     allow_unknown: false
